### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by mstambolija** [andrewisen/dj-requests#29]
Could you please explain how to properly install this app on my server? 
I've uploaded the master version to my server, created a Spotify app, added the .auth and .database files to the root folder, and created an SQL database on my server, but I can't get your app to work. Please help

**Comment by frisotrip** [comment]
I am also trying this toe work. They say you need basic understanding of php and ftp, but the manual is bad. Nothing about sql or how to install this.

**Comment by Aweponken** [comment]
Hi @mstambolija and @frisotrip. I see you're new users to GitHub, welcome.
This project isn't really maintained anymore, so there not much help to receive. Please also note that server specific implementation is way beyond what you can expect from these kind of discontinued open source projects.

> the manual is bad. Nothing about sql or how to install this.

There is literally a header in the readme with installation instructions. I just tried the Docker image and it works fine.
There is additional documentation in https://github.com/andrewisen/dj-requests/pull/28/.

**Comment by Aweponken** [comment]
Closing due to no response. Feel free to reach out if your have further questions @mstambolija @frisotrip.

**Comment by therealgena69** [comment]
Hi guys .... I'm like suck a baby when it comes to containers forks and builds and shit man 

Please can someone show me how this gets served on my own domain on my own FTP 
Docker image wont run 
PLEASE HELP
